### ISSUE TITLE
PHP container doesn't work when changing from the Nginx build to Apache and vice versa

### ISSUE THREAD

**Issue by leolandotan** [expresso-php/expresso-php#11]
## Issue
When I do a `docker-compose up -d` on the Nginx build and switch to the Apache build and run `docker-compose up -d`, it doesn't work.

This is due to the difference of the PHP service's installed packages and Docker setup. The Nginx' setup PHP service doesn't contain a web service unlike the Apache setup where it's PHP service has apache in it.

## Solution
My solution is to rename the PHP services for both branches so switching from different builds doesn't create an issue.

**Comment by Luukyb** [comment]
Merged work on the two branches.

Thanks @leolandotan
