### ISSUE TITLE
Cannot run docker-compose up -d on two projects at the same time

### ISSUE THREAD

**Issue by marychris** [expresso-php/expresso-php#14]
ERROR: for phpmyadmin  Cannot start service phpmyadmin: driver failed programming external connectivity on endpoint luukydrupalsandbox_phpmyadmin_1 (e9716a8d8c59611a15e22d016f55c2fee5716c72859ad82bc8fcf46df12ee7ad): Bind for 0.0.0.0:8181 failed: port is already allocated.

I git clone https://github.com/expresso-php/expresso-php.git for a new project and when I run docker-compose up -d afterwards, I got the error.
I docker-stopped the existing project I have and tried running docker-compose up -d again on the new project -- NO error.

**Comment by leolandotan** [comment]
Hi @marychris ,

I have updated the `docker-compose.yml` file to have a dynamic port for the phpMyAdmin service. Can you please confirm? :)

Thanks!

**Comment by Luukyb** [comment]
@marychris can you confirm that this is fixed? Thanks

**Comment by marychris** [comment]
Issue is fixed. Thanks @leolandotan !
