### ISSUE TITLE
"volumes_from" is deprecated for Docker Compose

### ISSUE THREAD

**Issue by lhridley** [expresso-php/expresso-php#23]
https://docs.docker.com/compose/compose-file/#volume-configuration-reference

With the addition of support for Docker Swarm to Docker Compose, the "volumes_from" service option is deprecated for Docker Compose version 3 yaml files.

These should be replaced with top level "volumes" declarations, and volume mappings to those within the various declared services.

**Comment by lhridley** [comment]
Addressed for the "nginx-php" branch with PR #24

**Comment by Luukyb** [comment]
This is now merged.
