### ISSUE TITLE
Wordpress configuration

### ISSUE THREAD

**Issue by marychris** [expresso-php/expresso-php#29]
**Context**
Expresso PHP is using PDO, but wordpress requires mysqli extension

**Objective**
Provide documentation on how to use expresso-php with wordpress

**Comment by Luukyb** [comment]
PR with inclusion of mysqli was provided by @icasimpan for both Apache and Ngnix.
Closing this ticket. We can open a new one later for documentation.
Thanks @marychris @icasimpan.
