### ISSUE TITLE
Setup for Apache + PHP

### ISSUE THREAD

**Issue by Luukyb** [expresso-php/expresso-php#3]
**Context**
The base of expresso PHP, simple docker drupal has an Apache setup. It needs to be ported to this project.

**Objective**
A branch with a working version of the setup: Apache + PHP 7 + Mariadb.

**Steps**
Grab the changes from the Apache branch.
https://github.com/Luukyb/simple-docker-drupal/tree/apache-php-5

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

I made some changes on the Apache setup and may need to be checked.

Please check changes on PR: https://github.com/expresso-php/expresso-php/pull/5

Please advise next steps to do if this needs further improvement. 

Thanks.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

I made some changes on the Apache setup and may need to be checked.

Please check changes on PR: https://github.com/expresso-php/expresso-php/pull/5

Please advise next steps to do if this needs further improvement. 

Thanks.

**Comment by Luukyb** [comment]
Merged your changes @johnrosswvsu.

Many thanks !
