### ISSUE TITLE
Package libpng12-dev is not available

### ISSUE THREAD

**Issue by leolandotan** [expresso-php/expresso-php#48]
Running `docker-compose up -d`  generates this error:
```
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

Based on my research libpng12-dev is no longer available in Ubuntu 16.10 and libpng-dev works.

We need to update the PHP Dockerfile.

**Comment by Luukyb** [comment]
Hi @leolandotan,
I tested on my local with Nginx and the error was not triggered, even with docker-compose build --force --no-cache. But I also tested with your branch, and it did not break anything. 
I merged your changes assuming it fixes an issue I do not see.
Let me know if there was extra steps to reproduce, so I can compare before and after your commit.
Thanks,
Luc

**Comment by leolandotan** [comment]
Hi @Luukyb ,

Nothing special. If you want to check the difference. At this time where the php service is using Ubuntu 16.10, you can turn `libpng-dev` to `libpng12-dev` and do a docker build. This will cause an error. Then you can change it back to `libpng-dev` and do a docker build again, this should not show any missing library error.

Hope everything is in order.

Thanks!

**Comment by Luukyb** [comment]
Hi @leolandotan,
I triggered a build before and after the change, and it did not change anything on my local.
Maybe my images are not up to date. I would need to delete them.
I will create another issue if I notice anything weird. So far, so good.
Thanks Leo,
Luc
