### ISSUE TITLE
PHP version issue

### ISSUE THREAD

**Issue by prometadmin** [expresso-php/expresso-php#51]
I'm a project manager and I have a dev who has this issue which needs some assistance:

_I've found this related drupal.org issue https://www.drupal.org/project/drupal/issues/2853503. I've tried adding the patch to the file at /web/docroot/composer.json and compiling it with `composer install` from /web/docroot, however it didn't get added to composer.lock. I'll keep working on this patch and researching this issue._

_Per https://github.com/expresso-php/expresso-php, I changed the first line of docker/php/Dockerfile from FROM php:7-fpm to FROM php:5-fpm and rerun `docker-compose up -d` and `docker-compose build --no-cache` however the PHP version is still at 7.1.11._

Thank you in advance!

**Comment by Luukyb** [comment]
Hi @prometadmin,
After changing the Dockerfile to "FROM php:5-fpm", can you try to run the following commands in that order:
1. `$ docker-compose build --no-cache --force`
2. `$ docker-compose up -d`

I think docker-compose up -d needs to happen after the docker-compose build.
Let me know,
Thanks,
Luc

**Comment by Luukyb** [comment]
Closing this ticket @prometadmin.
