### ISSUE TITLE
Composer Error: Failed to Build

### ISSUE THREAD

**Issue by acie** [expresso-php/expresso-php#58]
Error :  

> ---> Running in 06c531d7df2b
> Could not open input file: composer-setup.php
> ERROR: Service 'php_nginx' failed to build: The command '/bin/sh -c php composer-setup.php --install-dir=/usr/local/bin --filename=composer' returned a non-zero code: 1

Fix:
Removed these lines from the Dockerfile.

> RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> RUN php -r "if (hash_file('SHA384', 'composer-setup.php') ===                                                        '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo            'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

For this line.

> RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

Will be creating a PR for this.

**Comment by Luukyb** [comment]
Hi @acie ,
Thanks for reporting and providing the solution ;)
Tested and it worked.
This is now comited.
Thanks!
Luc
