### ISSUE TITLE
Package 'mysql-client' has no installation candidate in nginx-php

### ISSUE THREAD

**Issue by ardnet** [expresso-php/expresso-php#70]
I've encountered this error message below during `docker-compose up -d` in `nginx-php`:

```
Building dependency tree...
Reading state information...
Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-client' has no installation candidate
ERROR: Service 'php_nginx' failed to build: The command '/bin/sh -c apt-get update -qq   && apt-get install wget mysql-client -yq' returned a non-zero code: 100
```

**Comment by ardnet** [comment]
@Luukyb looks like this solved it: https://stackoverflow.com/questions/57048428/e-package-mysql-client-has-no-installation-candidate-in-php-fpm-image-build-u

Tested that on my local, and looks working, will post PR soon, cheers!

**Comment by Luukyb** [comment]
Tested and works great.
This is now merged. Thanks @ardnet !
