### ISSUE TITLE
Add Node.js installation script.

### ISSUE THREAD

**Issue by krisdarryn** [expresso-php/expresso-php#73]
Hi @Luukyb, I just leave this here as a message though this is not an issue I don't know where to put a suggestion.

I don't have permission to do PR, so I just leave the script here. I added this in `docker/php/Dockerfile`. 

```
# Install Node.js and npm.
# Refer to https://github.com/nodesource/distributions#debinstall for specific version to use.
RUN apt-get update && apt-get install curl \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install -y nodejs \
    && node -v \
    && npm -v
```

**Comment by Luukyb** [comment]
Hi @krisdarryn ,
I am not sure why you would need NodeJS and NPM on the docker container. What is the motive?

If this is for theming, like using Gulp, you would just install it on your local, not on the container. It's easier to maintain, give you more flexibility on the version and having it on the container will be slower than on your machine.

Thanks,
Luc
